layout=floating
floatingalpha=80
scalewindowed=1.25
scalefullscreen=1.25
vidscale=no
osd_margins=no
tick_delay_follow_display_fps=yes

unicodeminus=yes
icon_style=fluent

windowcontrols=no
audioonlyscreen=yes
tracknumberswidth=0

visibility_modes=auto_always
audio_track_mbtn_left_command=script-binding select/select-aid; script-message-to osc osc-hide
sub_track_mbtn_left_command=script-binding select/select-sid; script-message-to osc osc-hide
