MBTN_LEFT  cycle pause
MBTN_RIGHT script-binding select/context-menu

LEFT  seek -5;         script-message-to osc osc-show
RIGHT seek 5;          script-message-to osc osc-show
UP    seek 85;         script-message-to osc osc-show
DOWN  seek -85;        script-message-to osc osc-show
0     seek 0 absolute; script-message-to osc osc-show
u     revert-seek;     script-message-to osc osc-show
o     script-message-to osc osc-show
O     script-message-to osc osc-visibility cycle no-osd

+ add volume 5
- add volume -5

y add sub-delay -0.1

z    script-binding toggle-seeker
Z    script-binding paste-timestamp
/    script-binding commands/open
`    script-binding commands/open
TAB  script-binding skip-to-silence
