# Window
fullscreen=yes

# UI
osd-bar=no
osd-on-seek=no
osd-status-msg=Frame: ${estimated-frame-number} / ${estimated-frame-count}

# Playback position
save-position-on-quit=yes
watch-later-options-remove=vf,af

# yt-dlp
ytdl-format=bestvideo[height<=?1080]+bestaudio/best
# ytdl-raw-options=cookies-from-browser=firefox,mark-watched=

# Cache
cache=yes
cache-secs=100

# Video
vo=gpu-next,gpu
gpu-api=vulkan
hwdec=vulkan,vaapi

scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell

deband=yes
deband-iterations=2
deband-threshold=35
deband-range=16
deband-grain=5

# Audio
ao=pipewire
volume-max=150

# Subtitles
sub-visibility=no

# Language
alang=ja,en,hu
slang=en,hu


[anime]
sub-visibility=yes

# Scaling
glsl-shader=~~home/ArtCNN_C4F32.glsl
scale=ewa_lanczos
scale-blur=0.981251

# Luma down
dscale=catmull_rom

# Dithering
dither=error-diffusion
dither-depth=auto
error-diffusion=sierra-lite

# Antiring
scale-antiring=0.5
dscale-antiring=0.5
cscale-antiring=0.5

# Debanding
deband=yes
deband-iterations=4
deband-threshold=35
deband-range=16
deband-grain=4
