use_nerdfont = true
notify = true
shuffle = true
volnorm = true

[keybindings]
"í" = "seek -5s"
"y" = "seek +5s"

"gg" = "move up 500"
"G"  = "move down 500"

"Space" = "playpause"
"n" = "next"
"p" = "previous"

[theme]
highlight_bg = "#313244"
