use_nerdfont = true
notify = true
shuffle = true
volnorm = true

[keybindings]
"í" = "seek -5s"
"y" = "seek +5s"

"gg" = "move up 500"
"G"  = "move down 500"

"m"  = "voldown 100"
"M"  = "volup 100"
"gs" = "similar selected"

"Space" = "playpause"
"n" = "next"
"p" = "previous"

"+" = "volup 5"
"-" = "voldown 5"

[theme]
highlight_bg = "#313244"
