[general]
import = [ "~/.config/alacritty/theme.toml" ]
live_config_reload = false
ipc_socket = false

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "None"

[font]
size = 12

[selection]
save_to_clipboard = true

[cursor]
style = "Beam"
vi_mode_style = "Block"
blink_timeout = 0

[hints]
alphabet = "jfkdlséahgurieowpq"

[keyboard]
bindings = [
	{ key = "N", mods = "Control | Shift", action = "SpawnNewInstance" }
]
